name: CI
on:
  push: 
    branches:
       - main
  pull_request:
    branches:
      - main
    types:
      - assigned 
      - opened 
      - synchronize 
      - reopened

jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
