name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (i.e. v1.2.3)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          fetch-depth: 0

      - name: Fetch Version
        id: version
        run: |
          PLUGIN_VERSION="$(echo "${{ inputs.tag }}" | cut -d 'v')"
          echo "::set-output name=PLUGIN_VERSION::$PLUGIN_VERSION

      - name: Update Version
        run: |
          sed 's/version: ".*"/version: "${{ steps.version.outputs.PLUGIN_VERSION }}"/g' plugin.yaml
          sed 's/var Version = ".*"/var Version = "${{ steps.version.outputs.PLUGIN_VERSION }}"/g' cmd/dt/version.go
          git add plugin.yaml cmd/dt/version.go
          git commit -m 'Prepare release "${{ inputs.tag }}"'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Golang
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: 1.21

      - name: Build
        run: make build

      - name: Create tag
        run: git tag ${{ github.event.inputs.tag }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@336e29918d653399e599bfca99fadc1d7ffbc9f7 # v4.3.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
